





























































































































100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 246/246 [04:13<00:00,  1.03s/it]
  0%|                                                                                                                                                                                                                                                                                                                          | 0/155 [00:00<?, ?it/s]


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:05<00:00, 27.99it/s]
Traceback (most recent call last):
  File "MultiSageMix.py", line 397, in <module>
    torch.save(model.state_dict(), 'checkpoints/%s/models/model_three_point.t7' % args.exp_name)
  File "/home/ssawmya-local/.conda/envs/SageMix/lib/python3.7/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/ssawmya-local/.conda/envs/SageMix/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ssawmya-local/.conda/envs/SageMix/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/MultiSageMix/models/model_three_point.t7'